### ISSUE TITLE
Website architecture

### ISSUE THREAD

**Issue by theSage21** [PyJaipur/SoA#10]
# Website architecture

Please comment on this issue if you want to take up any of these tasks.

## Todo

- [x] architecture and deployment for soa website
    - [x] login mechanism
        - [x] login html
        - [x] state management
        - [x] gmail integration
        - [x] otp system
        - [x] rate limit signup api to prevent abuse
    - [x] profile page
        - [x] Account settings page
        - [x] certificate generation
    - [x] Track tasks on dashboard
        - [x] switch tracks
        - [x] switch track tasks
        - [x] task manipulation
        - [x] submit tasks
        - [x] task and track locking
    - [x] deploy to heroku
    - [x] get ssl certificates via letsencrypt and deploy to heroku

**Comment by Shivank98** [comment]
* We should keep the name same. SoA
### The website architecture.
      * Simple as CMI
### FOSS Project
      * Instead of finding three projects should we take PyJudge only?

**Comment by theSage21** [comment]
Please use numbered lists in the future so that replying to points is easier.

1. I'm thinking of using either [this template using tailwind css](https://www.tailwindtoolbox.com/templates/help-article-demo.php) or [this template from minicss](https://codepen.io/chalarangelo/project/full/DzvxKa).
2. PyJudge is not used by anyone. We need projects that people use on a daily basis so that the foss contribution is credible.

**Comment by Shivank98** [comment]
1. Template looks good for website. 

2. We can have a final call on flow of Program and start call for volunteers.

3. For FOSS projects pip has good collection of easy issue (still looking for more )

4. I Suggest if we have both solid flow of program and some sponsorship we should outsource the poster designing and promotions.

**Comment by anchal7299** [comment]
Email validation in login form needs to be done.

**Comment by theSage21** [comment]
Thanks for that catch. I'll add it to the work in #11

**Comment by Shivank98** [comment]
There is a package in lock file `pyDNS`. I am not sure if we require that we already have `py3dns`. keeping that in the lock file giving error as `pydns`  is not available for python3

**Comment by theSage21** [comment]
My mistake. I was trying to get email validation to work. The latest part of this branch should be good to go now.

Also, this work is complete :partying_face: and you can check it out at soa.pyjaipur.org.
Please let me know if something's missing.
